### ISSUE TITLE
Report about updates for extensions and the TYPO3 core

### ISSUE THREAD

**Issue by wowaTYPO3** [jweiland-net/jwtools2#30]
The extension checks in a freely configurable interval whether there are updates for active extensions or the TYPO3 core and sends a report to one or more definable e-mail addresses. The result of the check can also be viewed in the reports backend module.

**Comment by froemken** [comment]
Hi @wowaTYPO3 

I just have added a new ReportProvider which will show updatable extensions in reports module if EXT:reports is installed and activated. Further you have to activate that feature in ExtensionSettings.
As we use the ExtendedInterface all these information are available in mail of reports task, too.

Have fun using jwtools2

Stefan

**Comment by froemken** [comment]
Hi @wowaTYPO3 

I have set the severity of updatable extensions to INFO only. So, if you want to be informed about them by mail you should activate "send ALL reports instead of just ERROR/WARNING" in reports scheduler task.
