### ISSUE TITLE
Error Use SQL-Query Task

### ISSUE THREAD

**Issue by NightMeer** [jweiland-net/jwtools2#69]
I have enabled "Enable SQL-Query Task" to run a SQL query regularly. Under the "JW Tools" tab, I still see the following:

![image](https://github.com/jweiland-net/jwtools2/assets/44423095/2bfbf8a7-bfc7-4f27-b44f-c5207ff1a58f)

When I create a task in the scheduler, I receive the following error:
"The given severity level "info" for writerConfiguration of logger "JWeiland.Jwtools2.Task.ExecuteQueryTask" is not valid."

![image](https://github.com/jweiland-net/jwtools2/assets/44423095/d3fac3a4-a2e4-439e-b4f7-a556685f4485)

Version: 5.10.2

**Comment by sfroemkenjw** [comment]
Hello @NightMeer 

can you please add your TYPO3 version, too?

Stefan

**Comment by NightMeer** [comment]
Oh yea Sorry,

Typo3 Version: 9.5

**Comment by sfroemkenjw** [comment]
Hello @NightMeer 

thank you. I have solved that issue and released version 5.10.3:
https://extensions.typo3.org/extension/jwtools2

Stefan
